### ISSUE TITLE
add Github account creation to  setup page

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#10]
file to edit: [setup.md](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio/blob/gh-pages/setup.md)

**Comment by torwhite** [comment]
add more details on creating GitHub account

**Comment by ilessing** [comment]
@torwhite Do you think what I added is sufficient ?

see commit:  55a9707

**Comment by ilessing** [comment]
Torin and I talked about this and we think this is good as is.  
Closing this issue.
