### ISSUE TITLE
Setup: Add script to run in RStudio before workshop that installs all packages needed for R Markdown documents

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#110]
Forgot to add this, we can do it for a subsequent workshop

Last time we taught R Markdown, a learner commented that they would rather install this beforehand because it took a while during the workshop:

![image](https://user-images.githubusercontent.com/58574172/156283303-a24715d4-fc3b-4ad2-b1d6-8ad19dc780af.png)

**Comment by torwhite** [comment]
It took 2 min to install on my personal laptop

**Comment by rcurty** [comment]
I think that is ok to wait a few minutes,  since many learners with no Rstudio experience might find it a little complicated to follow by themselves, and we would have people behind anyways.

**Comment by torwhite** [comment]
we will leave as is (the package install for first time R markdown will be initiated during the workshop). Closing the issue.
