### ISSUE TITLE
ep. 3 edit language in knitr section

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#112]
> We’ll just use the generic template, but when we’re working on our own project, knitting periodically while we’re editing allows us to catch errors early. We’ll continue rendering our rmd throughout the lesson to see what happens when we add our markdown and knitr syntax and to make sure we aren’t making any errors.

That was true in the old workshop. Less so this one.

**Comment by rcurty** [comment]
I believe this issue was already taken care of. I did not find this text.
