### ISSUE TITLE
ep 5. Git not detected on system path

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#114]
Must add step in episode 5 to add git in Rstudio:

https://support.rstudio.com/hc/en-us/articles/200532077?version=2022.02.0%2B443&mode=desktop

**Comment by ilessing** [comment]
see also #115

**Comment by ilessing** [comment]
When I examine the Global Options for Git on a fairly fresh MacOS the _Git Executable_ was already filled in with:  
`/usr/bin/git` which is correct.

<img width="591" alt="MacOS-git-global-options-Screen Shot 2022-03-02" src="https://user-images.githubusercontent.com/275899/156447992-e8ee14ea-3cc1-4dfa-a25f-e0bcd1b5c043.png">
