### ISSUE TITLE
Setup: Windows users must install Git before workshop

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#115]

**Comment by ilessing** [comment]
This may be necessary on MacOS as well.  If I can find a mac that does not yet have `git` installed so I can test.

**Comment by ilessing** [comment]
MacOS has `git` pre-installed by default so this is not an issue on MacOS.
```sh
which git
/usr/bin/git
```

**Comment by torwhite** [comment]
Thanks, I will need to add this to the episode as well - system path for both mac and windows.

**Comment by torwhite** [comment]
added mac and windows path examples to ep. 5
