### ISSUE TITLE
ep. 6 Explain difference between unformatted url and markdown formatted link

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#118]
When looking at FIXME 2 for the doi hyperlink, it barely appears different in the visual mode to have it formatted as a link or not. 

Demonstrate the difference by knitting the document with the link unformatted and with the link formatted.

**Comment by rcurty** [comment]
I tested it again and seems to work fine. It highlights in blue and underlines the linked text in the rmd and when we knit the only difference is that the blue is a little lighter and that the underline only shows when we hoover the mouse over.
