### ISSUE TITLE
ep. 6 Creating Tables section confusing

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#121]
"Because creating tables manually in Rmd documents could be a little painful for beginners, Rstudio released an add-in functionality for tables back in 2018. The new visual editor, however, have made the process to create rmd tables more similar to other editors we use daily. In our template, we have the specification table with 10 rows and two columns (FIXME3). If we were willing to add that table, we could do that by inserting a table to a selected part of the documents and by specifying the desired number of rows and columns. Including a caption is optional, but recommended. We can add or delete rows and columns, add a header that will be set bold by default but can be changed, and set the desired alignment. **Select the desired text and click on the crossed T icon if you wish to clear formatting."**

the last part especially I am not sure of , select what text and where is the crossed T icon?

**Comment by rcurty** [comment]
Added a figure
