### ISSUE TITLE
ep. 6 inline code file path error

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#122]
The CSV file contains choice consistency data for ` r nrow(bronars_simulation_data.csv) ` simulated participants.

path should be "../../data/bronars_simulation_data.csv" - this allows the document to knit, but the # of rows does not display in the final document. 

Need to troubleshoot this. 

maybe the data needs to be load first? and then use nrow on the dataframe?

Yes, data needs to be loaded first: 

`r bronars_data <- read.csv("../../data/bronars_simulation_data.csv")`

and then:

`r nrow(bronars_data)`

or something to that effect. 

In the next episode we see how to globally load data so that the first expression isn't necessary. There may be a better way of doing this in the future? Maybe teach code chunks episode first and then styling?

**Comment by rcurty** [comment]
Will have to re-run it again tomorrow.

**Comment by rcurty** [comment]
I have followed the same process I tested multiple times in the past (using the import data set function and also the function to load the file which both worked when I developed the lesson), but I am still getting "an object not found error". I thought would be an easy fix to add that step, but not sure what else to do.

**Comment by rcurty** [comment]
It works on the console, but not in the markdown file as it used to.

**Comment by rcurty** [comment]
```{r}
library(readr)
bronars_simulation_data <- read_csv("data/bronars_simulation_data.csv")
```
 then,

replace 10.000 by 

`r nrow(bronars_simulation_data)`


Still need help to make the dataset not visible when render

**Comment by torwhite** [comment]
@rcurty I would suggests using the base R read csv function (read.csv()) instead of loading readr to use read_csv(). 

r bronars_data <- read.csv("../../data/bronars_simulation_data.csv")

**Comment by torwhite** [comment]
For the purposes of episode 6 you could just have learners load the data through the console (instead of in the document) and then only use r `nrow(bronars_data)` in the R markdown paper - as long as we specify this is not yet a reproducible way to do it. Then, in episode 7 I will be showing how to globally load the data for the R Markdown documents.

**Comment by rcurty** [comment]
Oh ok, I was hoping to call in in R Markdown instead to render it correctly and for them to see what it would look like in the paper. I will do it through the console and tell them that is not the desirable way of doing it.  So, we will wait until episode 8 to get that right.

**Comment by rcurty** [comment]
you are not having issues with that piece when you knit on ep. 8 right?

**Comment by rcurty** [comment]
@torwhite  helped to troubleshoot this. We can't load the dataset in the console. All should be done in R Markdwon. We noticed it does not load it to the environment when we do it straight on R Markdown but it renders correctly.
