### ISSUE TITLE
ep. 7 custom knit option in yaml disables knit button options in IDE

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#125]
with this is the yaml:

knit: (function(rmdFile, encoding) { 
      out_dir <- '../output';
      rmarkdown::render(rmdFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(rmdFile), 
                        out_dir, 
                        'DataPaper-ReproducibilityWorkshop.html'))})

knit button options are grayed out: 

However, we need to change those options to change knit directory in episode 7. Seems to be one or the other as options....

**Comment by torwhite** [comment]
Although I couldn't find a knit option that worked before, I found this stackoverflow note: 

https://stackoverflow.com/a/51144177

that does work. 

Also this is more reproducible than changing the knit directory in the IDE

**Comment by torwhite** [comment]
```
```{r setup}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

```
```

**Comment by torwhite** [comment]
requires the rprojroot package however - add to installation at the beginning?

**Comment by ilessing** [comment]
Yes, I think we should add the `rprojroot` to our suite of packages to install

**Comment by ilessing** [comment]
fixed with commit 481076d56

**Comment by torwhite** [comment]
Thanks Ian

**Comment by torwhite** [comment]
with Ian's above commit 141a1e9c, this issue is fully addressed. 

Will still likely remove the Knit function from the yaml to add at end of ep, 7 because it will mess with a challenge in ep. 2/3.
