### ISSUE TITLE
ep 5 figure should have the SSH URL rather than HTTPS

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio#127]
in [episode 5](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/05-setup-versioning/index.html#our-turn) when it is shown how to get the URL for a Github repository learners need to get the SSH version of the URL rather than the HTTPS one if they want to be able to PUSH and PULL from that repo in [episode 9 Github](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/09-github/index.html)

![](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/fig/05-copy-repo.PNG)

It is a bit of a problem though as they probably can not clone using an SSH URL until they have their SSH public key configured in Github and that isn't covered until episode 9.    Drat!

**Comment by ilessing** [comment]
This probably does NOT need to be addressed until after March 4th 2022

**Comment by torwhite** [comment]
I used HTTPS to set it up to start, and was still able to push to GitHub in episode 9.

**Comment by ilessing** [comment]
I tried cloning a repo using the HTTPS version of the repo URL and then I made a change, committed it and attempted to _push_ and I was prompted for username and password but that did NOT let me authenticate and push.

```
$ git push
Username for 'https://github.com': ilessing
Password for 'https://ilessing@github.com': 
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/ilessing/R-repro-pub.git/'
```

I think this IS going to be a problem for Day 2 of workshop in Episode 9.

**Comment by jonjab** [comment]
You haven't set your bashgit to take your PAT?

This will affect anyone who wants to push from the command line who hasn't used it since PW access got turned off last august.

**Comment by ilessing** [comment]
We want learners to be able to push using R-studio GUI  not command line Git.

**Comment by ilessing** [comment]
In workshop today we had learners clone their repos using an HTTPS URL.

In Episode 9 I'll be showing learners how to Authenticate with Github using SSH.

I was worried they would NOT be able to push to their git repo with an HTTPS URL after we set them up with SSH authentication in Episode 9.
So I did some experimentation and it is true that you can not push to an HTTPS Github URL using SSH authentication.

There are a few ways to solve this:

1. Have learners re-clone the repo using SSH URL.
2. Have learners change the remote URL for their repo from HTTPS to SSH
3. Have learners create a Personal Access Token (PAT) in their Github settings and use that as a password when authenticating to Github.

I think all of the above options may be confusing.

Anyone have an opinion on which of these would be best and why?

**Comment by ilessing** [comment]
I chose option 2 after a conversation in Slack with @rcurty who's pointed question was spot on.  
> which option is the least number of steps?

see commit: 10608bff61f6

**Comment by ilessing** [comment]
> I used HTTPS to set it up to start, and was still able to push to GitHub in episode 9.

@torwhite    I was not able to replicate that behavior.

**Comment by ilessing** [comment]
This issue will be nullified if we switch from SSH to PAT as our Github authentication method.
