### ISSUE TITLE
ep. 8 First two images are duplicates

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#130]
Is this intentional? Doesn't seem necessary

**Comment by torwhite** [comment]
That was actually in ep. 8. You removed an image in ep. 7 (which was redundant but I think was helpful)

**Comment by ilessing** [comment]
I found this same problem in episode 7 with the screenshot of [empty code chunk](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio/blob/main/fig/07-blank-code-chunk.PNG)

I removed the second one with commit e2267d09f39

**Comment by torwhite** [comment]
ok.

**Comment by rcurty** [comment]
removed duplicated image.
