### ISSUE TITLE
ep.8 challenge 8.1 can't find reference to tidyverse in the paper

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#131]
I only found the word "tidyverse" within code chunks which is not a place we can add citations.

**Comment by rcurty** [comment]
@torwhite Not sure what you are referring to. Line  162. There is a reference to Tidyverse "All analyses were conducted in R[^1] in the RStudio IDE[^2] using the packages Tidyverse **@wickham2019**, stringi[^3], BayesFactor[^4] and patchwork[^5].
That is the original paper note about their analysis. I have reworded the challenge and hopefully, it will be clearer now. If not, please feel free to re-open this.
