### ISSUE TITLE
ep. 8 challenge 8.4 Issue add cross ref for Figure 2

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#135]
See Figure 2 - I'm not sure that we can cross ref figure 2 because it's only a markdown image. It seems I can only cross ref Figure 3 or 4 that were added with code chunks

Also the text to search for figure 2 was not correct.

**Comment by rcurty** [comment]
This was a last-minute decision. Not to cover cross-referencing this time.
