### ISSUE TITLE
ep. 9 - Use PAT for GitHub Authentication

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio#151]
PAT for GitHub authentication rather than SSH (firewalls, security, etc. made it more complicated than anticipated)

**Comment by ilessing** [comment]
Torin uploaded new screenshots: 9819d5e2efa822d61

**Comment by ilessing** [comment]
major revisions to this episode are complete.  We can open new issues for anything else that crops up.
