### ISSUE TITLE
e. 7 - Simpler rmd file

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio#153]
Consider creating a separate prepared simpler Rmd file with a place to copy code (generic document) so that learners can toggle on and off options and see how it will play out without the delay of the lengthy knitting process. Then, move back to the working paper rmd file to complete the challenges.

**Comment by torwhite** [comment]
episode flow has been re-arranged and #167 addresses starting a new generic document for the demonstration.
