### ISSUE TITLE
Ep.05 - Figs 1 & 2

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio#18]
We need to provide these two figures to learners so that they can easily browse and include them in the manuscript.

**Comment by rcurty** [comment]
They are in the Figs folder for now.

**Comment by torwhite** [comment]
The figs for the manuscript are in the fig folder of r-repro-pub that learners will be cloning. All files necessary for the rendering of the paper should be there.

https://github.com/UCSBCarpentry/R-repro-pub/tree/main/report/source/fig
