### ISSUE TITLE
Re-number figs

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#184]

**Comment by torwhite** [comment]
#158 completed to renumber episodes to accomodate splitting the code chunk episode up. Now figs need to be re-numbered. The figure numbers in the fig folder should be correct up until (around halfway through) 07-xxx. However, might as well wait to re-number until screenshots have been re-done. Ideally much of the re-numbering can be done while re-doing the screenshoots.

**Comment by ilessing** [comment]
@torwhite Thanks for finishing this up!  

I was heads down on another project that I needed to complete before I could work on this issue.

I think this is ready for a merge/pull request.

**Comment by ilessing** [comment]
fixed with #198
