### ISSUE TITLE
Episodes 7 and 8 not rendering on the website or locally on jekyll

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#195]
Specifically, episode 8 is not displayed. @ilessing maybe you can do the thing again to make it work?

**Comment by ilessing** [comment]
![Screen-Shot-2022-05-13-at-3 44 13-PM](https://user-images.githubusercontent.com/275899/168398402-0481b811-f04d-4647-87f7-4dc2a317cd43.png)

BOM = [Byte order Mark](https://en.wikipedia.org/wiki/Byte_order_mark)  

> BOM use is optional. Its presence interferes with the use of [UTF-8](https://en.wikipedia.org/wiki/UTF-8) by software that does not expect non-ASCII bytes at the start of a file but that could otherwise handle the text stream.


found [how-can-i-remove-the-bom-from-a-utf-8-file](https://unix.stackexchange.com/questions/381230/how-can-i-remove-the-bom-from-a-utf-8-file) Which gave me: 

```
mv 08-code-chunks.md 08-code-chunks_with_BOM.txt 
sed $'1s/\xef\xbb\xbf//' < 08-code-chunks_with_BOM.txt > 08-code-chunks.md
rm 08-code-chunks_with_BOM.txt 
```

**Comment by ilessing** [comment]
https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/08-code-chunks/index.html works now
