### ISSUE TITLE
Reconcile md and rmd episodes

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio#196]
Before we submit it to the incubator perhaps we should reconcile rmd and md episodes. All recent edits were performed in md which is ok for learners, but might be confusing for lesson developers and maintainers.

**Comment by torwhite** [comment]
Unless we decide to edit with Rmd files moving forward, we should just delete the rmd files. We can only automatically generate md files from rmd files, but not the other way around, so if we primarily edit the md files the rmd will perpetually be behind. 

Unfortunately, for the new upcoming workshop template, it is designed to work with .Rmd only, so we may need to go back and manually create .Rmd files later on.

**Comment by ilessing** [comment]
agree we should delete the `.rmd` files from the repo

**Comment by torwhite** [comment]
We will reconcile the rmd and md files by deleting the rmd files

**Comment by torwhite** [comment]
#203  is the follow up issue.
