### ISSUE TITLE
Homepage/prereq: missing text 

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/Reproducible-Publications-with-RStudio#27]
Prerequisites and Home page introduction missing and has FIXME

**Comment by ilessing** [comment]
On [Homepage](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/)

file to edit:  [index.md](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio/blob/gh-pages/index.md)

![issue27Screen Shot 2022-02-18 at 12 20 54 PM](https://user-images.githubusercontent.com/275899/154756567-ded1c172-4388-463a-b1fd-87c979cc13f1.png)

**Comment by rcurty** [comment]
Sure, I will take care of that.
