### ISSUE TITLE
ep. 3 remove challenge 2.3

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#3]
It doesn't fit there since we've switched to the visual editor. 

Could fit in episode 2 when discussing source editor - optional section?

**Comment by ilessing** [comment]
[challenge 2.3 in episode 3](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/03-rmarkdown-file/index.html#challenge-23---formatting-with-symbols-optional)

![issue-3-Screen Shot 2022-02-18 at 1 57 57 PM](https://user-images.githubusercontent.com/275899/154768424-77535277-7844-44ce-ae21-d68e4689dbfa.png)

**Comment by torwhite** [comment]
moved after screenshot of source editor in ep. 2
