### ISSUE TITLE
ep 2. Clarification on visual editor mode

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/Reproducible-Publications-with-RStudio#30]
Amelia didn’t see a spot that actually says how to change into Visual Editor mode. 
(though it is mentioned later in Workshop). Is it better to have it in this episode or just keep it as is?

**Comment by ilessing** [comment]
[Episode 2 - Visual Editor -vs- Source editor](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/02-basic-rstudio/index.html#visual-editor-vs-source-editor)

**Comment by torwhite** [comment]
I think Ian's edit looks great, closing the issue.
