### ISSUE TITLE
ep. 3: the screenshot has a fixme 

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/Reproducible-Publications-with-RStudio#31]
Under part ‘1. YAML header’ the code snapshot has a ‘#FIXME make sure this matches final paper version’. Is this fine as is or do we need to change it? 
<img width="883" alt="this thing" src="https://user-images.githubusercontent.com/48770663/154376632-b98d5dea-b5c5-4e7a-b288-9734eecd0600.PNG">

**Comment by torwhite** [comment]
fixed, but will leave an issue open because I think there will be an addition to the yaml (saving html output to separate directory)
