### ISSUE TITLE
ep. 3 rticles challenge

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#34]
there’s an incomplete challenge with a ‘FIXME’

**Comment by ilessing** [comment]
in email @rcurty wrote:

>

Renata fixed #34 with commit 6d115f01cce632f93aef On Feb 22nd

but the fix was overwritten later by @torwhite with commit 52a9f67fc7ffae6006295b0

**Comment by ilessing** [comment]
I think I've got this fixed now with commit: 61128089cbf35fee3fc65d294969298a12fc21fe
![IMG_0E3023F55565-1 2](https://user-images.githubusercontent.com/275899/155607323-7d4dda72-24a6-4f2f-91df-f98ee4b6cd61.jpeg)
