### ISSUE TITLE
ep. 3 delete discussion at end of episode

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#35]
The ‘Discussion’ directly below reads incomplete. 

Seems like we don't need it.

**Comment by ilessing** [comment]
I think this must be about [episode 3](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/03-rmarkdown-file/index.html#discussion-what-are-the-pros-and-cons-of-using-a-template-optional)

![issue35-Screen Shot 2022-02-18 at 1 49 56 PM](https://user-images.githubusercontent.com/275899/154766252-d15ed29e-7c5d-4926-afa9-7c5197e5f3a3.png)

**Comment by torwhite** [comment]
yes, in episode 3

**Comment by ilessing** [comment]
reopening to re-apply commit:    52406c3b4052b9
that somehow got overwritten or something.
