### ISSUE TITLE
ep. 2 missing image "02-visual-editor-spotlight.png"

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#63]
I believe Ian created a spotlighted image for the visual editor. However, the image isn't in the fig folder

missing from ep.2 approximately line 143

**Comment by ilessing** [comment]
I re-added the screenshot in commit eae930857dbcd

closing.

**Comment by ilessing** [comment]
and then I had to move the screenshot to the `fig/` directory with commit. c969657
