### ISSUE TITLE
ep. 6 has multiple FIXMEs

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio#66]

**Comment by torwhite** [comment]
The FIXMEs are supposed to be there to indicate edits the learners will do as part of the workshop. Since this question has come up several times, does it make sense to label them something else?

**Comment by ilessing** [comment]
'grep -o FIX _episodes/06-writing-styling.md |wc -l`
       **9**

**Comment by torwhite** [comment]
@ilessing would you suggest calling them something else? They are supposed to be markers for where learners will make edits in the workshop paper.

**Comment by ilessing** [comment]
Oh... if Only I had read the lesson!  I'm a dork.  Let's just leave them as FIXMEs.
