### ISSUE TITLE
ep. 4 add screenshot of directory structure instead of markdown-formatted list

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#69]

**Comment by ilessing** [comment]
Good Idea!

**Comment by ilessing** [comment]
This one is more comprehensive:
![04-directory-tree2](https://user-images.githubusercontent.com/275899/155641963-87c4e136-f7c1-4725-96e3-f4762e3b6280.png)

made on https://carbon.now.sh/

**Comment by torwhite** [comment]
That looks great! Didn't know there were tools for that!



Torin White

They/Them

Data Science Librarian

Bridge to the Faculty Research Scholar

University Library

P: (312) 996-5551

E: ***@***.******@***.***>

S. Morgan St. | 1330 UH, MC 288 | Chicago, IL 60607



[cid:db90f4bc-b385-48dd-b547-1b67fb34063c]
________________________________

**Comment by ilessing** [comment]
added a screenshot of the directory tree in commit 7c7421f

closing.
