### ISSUE TITLE
ep. 4 add keypoints

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio#75]
Episode 4 needs key points added to the markdown frontmatter.

  these show up at the very bottom of the episode when it is rendered on [the website](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/04-good-project/index.html)

similar to #72

**Comment by torwhite** [comment]
Echelle comment:

Keypoints need to be added. Maybe things like: 1) Use best practices for file and folder organization. This includes using relative file paths as opposed to complete file paths. 2) Make sure that all data are backed up on multiple devices and that you treat raw data as read-only. 3) We can use Git and Github to keep track of what we've done in the past, and what we plan to do in the future. 4) Rproj files are pivotal to keeping everything bundled and organized.

**Comment by rcurty** [comment]
added
