### ISSUE TITLE
ep. 7  use of backticks (```) for code chunks in visual editor

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#77]
In the Code Chunks section: "They are surrounded by three tick marks on either side (```) with the starting three tick marks followed by curly brackets {}with some other code inside." This might be confusing, since we're having the learners use the visual editor mode, and the ``` are only visible in the source editor.

**Comment by ilessing** [comment]
so I think the problem here is the current version of the screenshot
![07-blank-code-chunk](https://user-images.githubusercontent.com/275899/155814869-9e59c49e-dd6f-480e-a39b-19e44f0fda55.PNG)

 shows how R Studio displays a code chunk when your are NOT in visual editor mode.
