### ISSUE TITLE
ep. 5 add keypoints

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#81]
Keypoints need to be added. Maybe things like: 1) Git versioning can be used in combination with GitHub and RStudio for easy tracking of changes. 2) Always remember to pull data before you start your working session, commit changes frequently, and push data back to GitHub before you sign off for the day!

**Comment by kristi-sara** [comment]
Comments were pre  2/24 edits. Kristi closing
