### ISSUE TITLE
Run through workshop with mac setup

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#96]
Use 'fresh' install of R/RStudio on a mac.

Do all hands on steps learners are instructed to do. Make sure the steps make sense, no steps are missed or that there aren't any other obstacles

**Comment by ilessing** [comment]
- nothing for learners to do in episode 1.
- [episode 2]( https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/02-basic-rstudio/index.html#challenge-21---installing-packages)
  - got message "Do you want to install from sources the package which need compilation? (Yes/no/cancel)"  I chose _No_

**Comment by ilessing** [comment]
in [episode 3](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/03-rmarkdown-file/index.html#4-rendering-your-rmd-document) the first time I hit the _knit_ button I got error:
```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘rlang’ 0.4.5 is being loaded, but >= 0.4.10 is required
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

**Comment by ilessing** [comment]
I was able to solve this by un-installing the `0.4.5` version of the `slang` package.  Somehow I had two of them.  
<img width="445" alt="2-versions-of-rlang-package-Screen Shot 2022-03-02" src="https://user-images.githubusercontent.com/275899/156424401-e9aacff7-e7e9-4f30-9580-a44ca3f15dd1.png"> 

I'm guessing this is NOT the sort of thing likely to come up in workshop but if it does it will likely need a one-on-one session with a helper in a breakout room

**Comment by ilessing** [comment]
When I tried to _knit_ my "Biometrics Journal" template I got error:
```
/Users/stnduser/Applications/RStudio.app/Contents/MacOS/quarto/bin/pandoc +RTS -K512m -RTS bio-paper.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output bio-paper.tex --lua-filter /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --template /Users/stnduser/Library/R/3.5/library/rticles/rmarkdown/templates/biometrics/resources/template.tex --highlight-style tango --pdf-engine pdflatex --natbib 
output file: bio-paper.knit.md

! LaTeX Error: File `endfloat.sty' not found.

! Emergency stop.
<read *> 

Error: LaTeX failed to compile bio-paper.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See bio-paper.log for more info.
In addition: Warning message:
In normalizePath(dirname(f)) : path[1]="NA": No such file or directory
Execution halted
```

**Comment by ilessing** [comment]
I've sought quite a few solutions to the LaTeX missing style file issue above without any success.
[This Tex.stackexchange](https://tex.stackexchange.com/questions/64133/sty-file-not-found) with the solution for MacOS was quite promising but I was not able to complete it.  
[endfloat.sty](https://fenrir.naruoka.org/download/autopilot/TeX/endfloat.sty)

**Comment by ilessing** [comment]
I think I may have caused my above _Knitting_ problem by answering "NO" to the question ""Do you want to install from sources the package which need compilation? (Yes/no/cancel)"  that pops up in the console when I installed packages.  
@rcurty answered "YES" to that question so I'll be interested to hear if she encounters an error when Knitting a markdown doc from the Biometrics Journal template.

**Comment by ilessing** [comment]
in [episode 6 - adding inline code](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/06-writing-styling/index.html#challenge-61---adding-inline-code) challenge  
When I added the code from the solution and _knitted_ I got error:
```
Error in mean(brokers_simulation_data$violation_counts):
  object 'bronars_simulation_data' not found
Calls: ,Anonymous> ... inline_exec -> hook_eval -> withVisible -> eval -> eval -> mean
Execution halted.
```
<img width="1551" alt="ep6-knit-error-Screen Shot 2022-03-02 at 4 11 48 PM" src="https://user-images.githubusercontent.com/275899/156471690-5a015f52-3ac4-4617-9d35-66ff7825352e.png">

**Comment by rcurty** [comment]
Yes, there is a separate issue for this. We have to include to call the data folder. I am working on that.

**Comment by ilessing** [comment]
I guess you mean #126

**Comment by torwhite** [comment]
@ilessing do you think we can close this issue? Anything still unresolved? 

I think the issue with mac package installation might need to be addressed? (would need to be included in the setup instructions for R packages):

"Do you want to install from sources the package which need compilation? (Yes/no/cancel)"

**Comment by ilessing** [comment]
This issue is probably specific to the BioMetrics template and so has limited importance for the workshop.  Let's NOT adjust the lesson for this particular error.

> When I tried to _knit_ my "Biometrics Journal" template I got error:
> 
> ```
> /Users/stnduser/Applications/RStudio.app/Contents/MacOS/quarto/bin/pandoc +RTS -K512m -RTS bio-paper.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output bio-paper.tex --lua-filter /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --template /Users/stnduser/Library/R/3.5/library/rticles/rmarkdown/templates/biometrics/resources/template.tex --highlight-style tango --pdf-engine pdflatex --natbib 
> output file: bio-paper.knit.md
> 
> ! LaTeX Error: File `endfloat.sty' not found.
> 
> ! Emergency stop.
> <read *> 
> 
> Error: LaTeX failed to compile bio-paper.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See bio-paper.log for more info.
> In addition: Warning message:
> In normalizePath(dirname(f)) : path[1]="NA": No such file or directory
> Execution halted
> ```

**Comment by torwhite** [comment]
added any lingering issues or things to know to new issues.
